baseURL = "https://eevee.bot/"
languageCode = "en-us"
title = "eevee.bot"
sectionPagesMenu: primary

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    title = "eevee.bot"
    languageName = "English"
    weight = 10

[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]
  sans_serif_font = "Inter"     # Default is System font
  secondary_font  = "Inter"     # Default is System font
  mono_font       = "Fira Code" # Default is System font
  description     = "eevee.bot"

[params.docs]
  intLinkTooltip = true
  extLinkNewTab  = true
  prism          = true 
  prismTheme     = "lucario"
  title          = "eevee.bot"
  logoLinkURL    = "https://eevee.bot/docs"
  darkMode       = true
  themeColor     = "red"

[params.footer]
  copyright = "Attribution-NonCommercial-ShareAlike 4.0 International"

[params.social]
  github = "eeveebot"

[menus]
  [[menus.primary]]
    name = "Helm"
    url = "https://helm.eevee.bot"
    pre = '<img src="https://eevee.bot/landing/helm-mark.svg" alt="Helm Icon" class="icon" width="24" height="24">'
