---
kind: Kustomization
resources:
- crds/eevee.bot_connectorircs.yaml
- crds/eevee.bot_natsclusters.yaml
- crds/eevee.bot_natsclusters.yaml

- eevee_connectorirc.yaml
- eevee_namespace.yaml
- eevee_natsauth.yaml
- eevee_natscluster.yaml
- eevee_operator.yaml
- eevee_toolbox.yaml
